# 1/24

In [9]:
# cd = change directory, or enter the ___ directory from <cd ____>
# ls = list all files in directory
x = input()
print('The variable x has a value of'  + x)

 3


The variable x has a value of3


# 1/31

In [16]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ndim) # Shows how many dimensions in array (including 0 (scalar))
print(a.shape) # Shows how many coloumns and rows in array

# Arrays are typed 
# Arrays are dense objects
# Faster than python lists because less memory
# You can ONLY combine arrays of the same shape!

2
(2, 3)


Array Exercises:

In [26]:
import numpy as np

In [ ]:
# 1:
b = 

In [17]:
#2:
a = np.array([1, 2, 3, 4, 5, 6])
a = a.reshape(3, 2)
a = a.reshape(2, -1) # Rearranges ... somehow idk
a = a.ravel # Unravels the data
print(a)

<built-in method ravel of numpy.ndarray object at 0x106efbb70>


Transposition:

In [21]:
a = np.arange(10).reshape(5, 2) 
a = a.transpose((1,0)) # np.transpose rearranges axes
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
a = a.T # Everything in the first column now in the first row
a

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

Math, Universal Functions:

In [25]:
# Very prevalent
# Also called ufuncs
# Element-wise (distributes data over container)
# Examples:
# - np.exp
# - np.sqrt
# - np.sin
# - np.cos
# - np.isnan

np.sqrt(a)

array([[0.        , 1.41421356, 2.        , 2.44948974, 2.82842712],
       [1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ]])

Indexing:

In [27]:
# a[0, 0]    Top-left element
# a[0, -1]   First row, last column
# a[0, :]    First row (many entires)
# a[:, 0]    First column (many entires)

Pandas:

In [28]:
# Python module (library) used for data analysis and exploration
# Two main useful data structures:
#  - Series
#  - DataFrames

# CAN import data files and turn them into DataFrames
#  - CSV (comma-separated values)

# Handles, at most, medium-sized data 

# If you get stuck, look at documentation!

In [3]:
import pandas as pd
csv_df = pd.read_csv('cars.csv')
csv_df.head()

ModuleNotFoundError: No module named 'pandas'

# 2/12:

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('titanic_test_data.csv')
POI = df.Embarked.to_numpy()
Southhampton = (POI == 'S')
data = {'ID' : PassengerId,
        'Class' : Pclass,
        'Name' : Name,
        'Sex' : Sex,
        'Age' : Age,
        'Sibilings/Spouses' : SibSp,
        'Parents/Children' : Parch,
        'Ticket Number' : Ticket,
        'Ticket Price' : Fare,
        'Cabin' : Cabin}

# This don't work because you haven't converted to arrays, yet.

In [13]:
import pandas as pd
import numpy as np

df = pd.read_csv('titanic_test_data.csv')

df[df['Embarked'] == 'S'] # df[condition]... what you're applying condition to.

PassengerId  Pclass                                          Name  \
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5            897       3                    Svensson, Mr. Johan Cervin   
7            899       2                  Caldwell, Mr. Albert Francis   
..           ...     ...                                           ...   
409         1301       3                     Peacock, Miss. Treasteall   
412         1304       3                Henriksson, Miss. Jenny Lovisa   
413         1305       3                            Spector, Mr. Woolf   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   

        Sex   Age  SibSp  Parch              Ticket     Fare Cabin Embarked  
1    female  47.0      1      0              363272   7.0000   NaN        S  
3      male  27.0      0      0              315154   8.6625   NaN        S  
4    female  22.0      1      1             3101298  12.2875   NaN        S  
5      male  14.0      0      0                7538   9.2250   NaN        S  
7      male  26.0      1      1              248738  29.0000   NaN        S  
..      ...   ...    ...    ...                 ...      ...   ...      ...  
409  female   3.0      1      1  SOTON/O.Q. 3101315  13.7750   NaN        S  
412  female  28.0      0      0              347086   7.7750   NaN        S  
413    male   NaN      0      0           A.5. 3236   8.0500   NaN        S  
415    male  38.5      0      0  SOTON/O.Q. 3101262   7.2500   NaN        S  
416    male   NaN      0      0              359309   8.0500   NaN        S  

[270 rows x 11 columns]

# 2/19:

Supervised = Set of "correct" answers that the machine can check their predictions against
Unsupervised = Not that

What kind of problems can you solve with supervised?
- Identify spam... makes prediction if spam or not, tell it if it's right
- Reccomend products to customers, could have database of whether product is "right"... or if they buy it?
- Customer segments... customers could already be put into segments, it just needs to get the right

Discrete (Supervised) = Classification / Categorization

Discrete (Unsupervised) = Clustering

Continuous (Supervised) = Regression

Continuous (Unsupervised) = Dimensionality Reduction

Linear Regression: y = mx + b

Univariate = ONE x to predict y

Multivariate = MANY x to predict y

Mean Squared Error = Distance from observed point to predicted (difference), squared, all added together

R = Correlation between two variables

R^2 = Square of ^ (how close data is to regression line / model fits raw data)

^^ between 0 and 1

Classification - KNN:

Each data represents a "vote" which will make mystery data point look more like itself

"K" number is hyperparameter = how many points should be considered

Accuracy = Number of correct predictions / total predictions

(Know what a boxplot looks like)

# 2/21:

- Linear regression = predicitng value of y using models of x
- K-nearest neighbor is simply the number of rows/datapoints you analyze to determine an unknown point