# 1/24

In [1]:
# cd = change directory, or enter the ___ directory from <cd ____>
# ls = list all files in directory
x = input()
print('The variable x has a value of'  + x)

The variable x has a value of


# 1/31

In [2]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ndim) # Shows how many dimensions in array (including 0 (scalar))
print(a.shape) # Shows how many coloumns and rows in array

# Arrays are typed 
# Arrays are dense objects
# Faster than python lists because less memory
# You can ONLY combine arrays of the same shape!

2
(2, 3)


Array Exercises:

In [3]:
import numpy as np

In [4]:
# 1:
b = 

SyntaxError: invalid syntax (2246918383.py, line 2)

In [ ]:
#2:
a = np.array([1, 2, 3, 4, 5, 6])
a = a.reshape(3, 2)
a = a.reshape(2, -1) # Rearranges ... somehow idk
a = a.ravel # Unravels the data
print(a)

<built-in method ravel of numpy.ndarray object at 0x106efbb70>


Transposition:

In [ ]:
a = np.arange(10).reshape(5, 2) 
a = a.transpose((1,0)) # np.transpose rearranges axes
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [ ]:
a = a.T # Everything in the first column now in the first row
a

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

Math, Universal Functions:

In [ ]:
# Very prevalent
# Also called ufuncs
# Element-wise (distributes data over container)
# Examples:
# - np.exp
# - np.sqrt
# - np.sin
# - np.cos
# - np.isnan

np.sqrt(a)

array([[0.        , 1.41421356, 2.        , 2.44948974, 2.82842712],
       [1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ]])

Indexing:

In [ ]:
# a[0, 0]    Top-left element
# a[0, -1]   First row, last column
# a[0, :]    First row (many entires)
# a[:, 0]    First column (many entires)

Pandas:

In [ ]:
# Python module (library) used for data analysis and exploration
# Two main useful data structures:
#  - Series
#  - DataFrames

# CAN import data files and turn them into DataFrames
#  - CSV (comma-separated values)

# Handles, at most, medium-sized data 

# If you get stuck, look at documentation!

In [ ]:
import pandas as pd
csv_df = pd.read_csv('cars.csv')
csv_df.head()

ModuleNotFoundError: No module named 'pandas'

# 2/12:

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('titanic_test_data.csv')
POI = df.Embarked.to_numpy()
Southhampton = (POI == 'S')
data = {'ID' : PassengerId,
        'Class' : Pclass,
        'Name' : Name,
        'Sex' : Sex,
        'Age' : Age,
        'Sibilings/Spouses' : SibSp,
        'Parents/Children' : Parch,
        'Ticket Number' : Ticket,
        'Ticket Price' : Fare,
        'Cabin' : Cabin}

# This don't work because you haven't converted to arrays, yet.

In [ ]:
import pandas as pd
import numpy as np

df = pd.read_csv('titanic_test_data.csv')

df[df['Embarked'] == 'S'] # df[condition]... what you're applying condition to.

PassengerId  Pclass                                          Name  \
1            893       3              Wilkes, Mrs. James (Ellen Needs)   
3            895       3                              Wirz, Mr. Albert   
4            896       3  Hirvonen, Mrs. Alexander (Helga E Lindqvist)   
5            897       3                    Svensson, Mr. Johan Cervin   
7            899       2                  Caldwell, Mr. Albert Francis   
..           ...     ...                                           ...   
409         1301       3                     Peacock, Miss. Treasteall   
412         1304       3                Henriksson, Miss. Jenny Lovisa   
413         1305       3                            Spector, Mr. Woolf   
415         1307       3                  Saether, Mr. Simon Sivertsen   
416         1308       3                           Ware, Mr. Frederick   

        Sex   Age  SibSp  Parch              Ticket     Fare Cabin Embarked  
1    female  47.0      1      0              363272   7.0000   NaN        S  
3      male  27.0      0      0              315154   8.6625   NaN        S  
4    female  22.0      1      1             3101298  12.2875   NaN        S  
5      male  14.0      0      0                7538   9.2250   NaN        S  
7      male  26.0      1      1              248738  29.0000   NaN        S  
..      ...   ...    ...    ...                 ...      ...   ...      ...  
409  female   3.0      1      1  SOTON/O.Q. 3101315  13.7750   NaN        S  
412  female  28.0      0      0              347086   7.7750   NaN        S  
413    male   NaN      0      0           A.5. 3236   8.0500   NaN        S  
415    male  38.5      0      0  SOTON/O.Q. 3101262   7.2500   NaN        S  
416    male   NaN      0      0              359309   8.0500   NaN        S  

[270 rows x 11 columns]

# 2/19:

Supervised = Set of "correct" answers that the machine can check their predictions against
Unsupervised = Not that

What kind of problems can you solve with supervised?
- Identify spam... makes prediction if spam or not, tell it if it's right
- Reccomend products to customers, could have database of whether product is "right"... or if they buy it?
- Customer segments... customers could already be put into segments, it just needs to get the right

Discrete (Supervised) = Classification / Categorization

Discrete (Unsupervised) = Clustering

Continuous (Supervised) = Regression

Continuous (Unsupervised) = Dimensionality Reduction

Linear Regression: y = mx + b

Univariate = ONE x to predict y

Multivariate = MANY x to predict y

Mean Squared Error = Distance from observed point to predicted (difference), squared, all added together

R = Correlation between two variables

R^2 = Square of ^ (how close data is to regression line / model fits raw data)

^^ between 0 and 1

Classification - KNN:

Each data represents a "vote" which will make mystery data point look more like itself

"K" number is hyperparameter = how many points should be considered

Accuracy = Number of correct predictions / total predictions

(Know what a boxplot looks like)

# 2/21:

- Linear regression = predicitng value of y using models of x
- K-nearest neighbor is simply the number of rows/datapoints you analyze to determine an unknown point

# 2/28:

In [ ]:
# Hi!

## 3/20:

In [ ]:
# Puts all even numbers through 1000 in a list:

even_numbers_through_1000 = [x for x in range(1001) if x % 2 == 0]
even_numbers_through_1000

[0,
 2,
 4,
 6,
 8,
 10,
 12,
 14,
 16,
 18,
 20,
 22,
 24,
 26,
 28,
 30,
 32,
 34,
 36,
 38,
 40,
 42,
 44,
 46,
 48,
 50,
 52,
 54,
 56,
 58,
 60,
 62,
 64,
 66,
 68,
 70,
 72,
 74,
 76,
 78,
 80,
 82,
 84,
 86,
 88,
 90,
 92,
 94,
 96,
 98,
 100,
 102,
 104,
 106,
 108,
 110,
 112,
 114,
 116,
 118,
 120,
 122,
 124,
 126,
 128,
 130,
 132,
 134,
 136,
 138,
 140,
 142,
 144,
 146,
 148,
 150,
 152,
 154,
 156,
 158,
 160,
 162,
 164,
 166,
 168,
 170,
 172,
 174,
 176,
 178,
 180,
 182,
 184,
 186,
 188,
 190,
 192,
 194,
 196,
 198,
 200,
 202,
 204,
 206,
 208,
 210,
 212,
 214,
 216,
 218,
 220,
 222,
 224,
 226,
 228,
 230,
 232,
 234,
 236,
 238,
 240,
 242,
 244,
 246,
 248,
 250,
 252,
 254,
 256,
 258,
 260,
 262,
 264,
 266,
 268,
 270,
 272,
 274,
 276,
 278,
 280,
 282,
 284,
 286,
 288,
 290,
 292,
 294,
 296,
 298,
 300,
 302,
 304,
 306,
 308,
 310,
 312,
 314,
 316,
 318,
 320,
 322,
 324,
 326,
 328,
 330,
 332,
 334,
 336,
 338,
 340,
 342,
 344,
 346,
 348,
 350,

In [ ]:
# And all those with 8 somewhere in there:

even_numbers_through_1000_with_8 = [num for num in even_numbers_through_1000 if '8' in str(num)]
even_numbers_through_1000_with_8

[8,
 18,
 28,
 38,
 48,
 58,
 68,
 78,
 80,
 82,
 84,
 86,
 88,
 98,
 108,
 118,
 128,
 138,
 148,
 158,
 168,
 178,
 180,
 182,
 184,
 186,
 188,
 198,
 208,
 218,
 228,
 238,
 248,
 258,
 268,
 278,
 280,
 282,
 284,
 286,
 288,
 298,
 308,
 318,
 328,
 338,
 348,
 358,
 368,
 378,
 380,
 382,
 384,
 386,
 388,
 398,
 408,
 418,
 428,
 438,
 448,
 458,
 468,
 478,
 480,
 482,
 484,
 486,
 488,
 498,
 508,
 518,
 528,
 538,
 548,
 558,
 568,
 578,
 580,
 582,
 584,
 586,
 588,
 598,
 608,
 618,
 628,
 638,
 648,
 658,
 668,
 678,
 680,
 682,
 684,
 686,
 688,
 698,
 708,
 718,
 728,
 738,
 748,
 758,
 768,
 778,
 780,
 782,
 784,
 786,
 788,
 798,
 800,
 802,
 804,
 806,
 808,
 810,
 812,
 814,
 816,
 818,
 820,
 822,
 824,
 826,
 828,
 830,
 832,
 834,
 836,
 838,
 840,
 842,
 844,
 846,
 848,
 850,
 852,
 854,
 856,
 858,
 860,
 862,
 864,
 866,
 868,
 870,
 872,
 874,
 876,
 878,
 880,
 882,
 884,
 886,
 888,
 890,
 892,
 894,
 896,
 898,
 908,
 918,
 928,
 938,
 948,
 958,
 968,
 

# 3/25:

In [5]:
def sorter(x):
    for x in range [1, x]:
        if x % 3 == 0:
            print(x, 'fizz')
        elif x % 5 == 0:
            print(x, 'buzz')
        elif x % 3 == 0 and x % 5 ==0:
            print(x, 'fizzbuzz')
        else:
            print(x)
        
sorter(15)

TypeError: 'type' object is not subscriptable

## 3/27:

Overfitting = A model predicts the patterns—or "noise–of the test dataset more than becoming a good predictor. By sticking too closely to this test set, it does a poor job at predicting outcomes for any other dataset.
- Model is too complicated

Underfitting = A model—likely for a lack of features or data to work off of—cannot predict outcomes accurately: it is overgeneralized.
- Model is too simple

Cross Validation = Testing a model's capacity to predict for data it was not based on.
- Prevents overfitting

As an aside, stratifying is maintaining the same proportion of Yes's / No's in your test as your training set.

## 4/3:

Bagging = Creating additional training data, combining to given data, bootstrapping—or randomly sampling from combined data—and training model on all that

Better Bagging Definition = Subsets of data may have lotta variance in them, so by 
- Data split into 3 different random chunks—w replacement—to train 3 different, respective models, which feed into final model
- Parallel

Better Boosting Definition = Data is used to train multiple models which are related to one another, and each model is given a weight in the final model aggregating all of them
- 1 random chunk of data, trains model, which affects final model AND affects new data, which is used to train new model... and on and on
- Each model does a good job at predicting different part of dataset
- Sequential

In [6]:
def swapper(list: list[int], pos1: int, pos2: int) -> list[int]:
    """Swaps elements at given positions in list"""
    list[pos1], list[pos2] = list[pos2], list[pos1]
    return list

example_list = [23, 41, 98, 900]
pos1, post2 = 0, 1

print(swapper(example_list, pos1 = 1, pos2 = 0))

[41, 23, 98, 900]


# 4/8:

AUC = Area under the "Receiving Operating Characteristic" (Curve)
- Precision vs. Recall if data imbalanced (and recall / precision BOTH matter)
- True Positive vs. False Positive rates if data balanced

In [8]:
def calculate_average(list: list[int]) -> float:
    average = sum(list) / len(list)
    print("The average is:", average)

awesome_list = [10, 20, 30, 40, 50] # Average is 30.0
calculate_average(awesome_list)

The average is: 30.0
