# 1/24

In [9]:
# cd = change directory, or enter the ___ directory from <cd ____>
# ls = list all files in directory
x = input()
print('The variable x has a value of'  + x)

 3


The variable x has a value of3


# 1/31

In [16]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ndim) # Shows how many dimensions in array (including 0 (scalar))
print(a.shape) # Shows how many coloumns and rows in array

# Arrays are typed 
# Arrays are dense objects
# Faster than python lists because less memory
# You can ONLY combine arrays of the same shape!

2
(2, 3)


Array Exercises:

In [26]:
import numpy as np

In [ ]:
# 1:
b = 

In [17]:
#2:
a = np.array([1, 2, 3, 4, 5, 6])
a = a.reshape(3, 2)
a = a.reshape(2, -1) # Rearranges ... somehow idk
a = a.ravel # Unravels the data
print(a)

<built-in method ravel of numpy.ndarray object at 0x106efbb70>


Transposition:

In [21]:
a = np.arange(10).reshape(5, 2) 
a = a.transpose((1,0)) # np.transpose rearranges axes
a

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [24]:
a = a.T # Everything in the first column now in the first row
a

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

Math, Universal Functions:

In [25]:
# Very prevalent
# Also called ufuncs
# Element-wise (distributes data over container)
# Examples:
# - np.exp
# - np.sqrt
# - np.sin
# - np.cos
# - np.isnan

np.sqrt(a)

array([[0.        , 1.41421356, 2.        , 2.44948974, 2.82842712],
       [1.        , 1.73205081, 2.23606798, 2.64575131, 3.        ]])

Indexing:

In [27]:
# a[0, 0]    Top-left element
# a[0, -1]   First row, last column
# a[0, :]    First row (many entires)
# a[:, 0]    First column (many entires)

Pandas:

In [28]:
# Python module (library) used for data analysis and exploration
# Two main useful data structures:
#  - Series
#  - DataFrames

# CAN import data files and turn them into DataFrames
#  - CSV (comma-separated values)

# Handles, at most, medium-sized data 

# If you get stuck, look at documentation!

In [3]:
import pandas as pd
csv_df = pd.read_csv('cars.csv')
csv_df.head()

ModuleNotFoundError: No module named 'pandas'